
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abc
 */
public class Student extends javax.swing.JFrame {
Connection connection=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form Student
     */
    DecimalFormat df = new DecimalFormat("0.00");
    int C,CP;
    double T,TP,OGPA;
    public Student() {
        connection=dbconnect.dbconnector();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 102));
        setMaximumSize(new java.awt.Dimension(1000, 667));
        setMinimumSize(new java.awt.Dimension(1000, 667));
        setSize(new java.awt.Dimension(1000, 667));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("NO. OF BACKLOGS IN THIS SEMESTER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("STUDENT PANEL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, 51));

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 290, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("STUDENT ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 51));

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 290, 30));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 120, 50));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("CALCULATE RESULT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 270, 50));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("PRINT RESULT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 270, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("SEMESTER NO.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 51));

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 170, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        mainpage m =new mainpage();
        Student.this.setVisible(false);
        m.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
    int a = Integer.parseInt(t1.getText());
    int b = Integer.parseInt(t2.getText());
    int count_update=0;
    String str,sub="";
    
    try
        {
           String query="select * from rps.marks,rps.course where rps.marks.cno=rps.course.courseno and rps.marks.rno=? and rps.course.semesterno=?;"; 
           String que="update rps.marks set backlog=1 where rno=? and cno=?";
           PreparedStatement pst=connection.prepareStatement(query);
           PreparedStatement ps=connection.prepareStatement(que);
           pst.setInt(1,a);
           pst.setInt(2,b);
            rs=pst.executeQuery();
                int ct,cp,count=0,cpp=0,mt,mm,mp,backlog=0;
                double total=0,tc=0,sgpa,ogpa=0;
                while(rs.next())
                {
                    str=rs.getString(2);
                    mt=rs.getInt(3);
                    mm=rs.getInt(4);
                    mp=rs.getInt(5);
                    ct=rs.getInt(15);
                    cp=rs.getInt(16);
                    
                    if((mp+mm)<40 && ct==0 && cp>0)
                    {
                        backlog++;
                        ps.setInt(1,a);
                        ps.setString(2,str);
                        count_update+=ps.executeUpdate();
                        sub=sub+" "+str+"(P)"+" ";
                        
                    }
                    else if((mt+mm)<40 && cp==0 && ct>0)
                    {
                        backlog++;
                        ps.setInt(1,a);
                        ps.setString(2,str);
                        count_update+=ps.executeUpdate();
                        sub=sub +" "+str+"(T)"+" ";
                        
                    }
                    
                    else if((mt+mm)<28 && ct>0)
                    {
                        if(mp<12 && cp>0)
                        {
                        backlog++;
                        ps.setInt(1,a);
                        ps.setString(2,str);
                        count_update+=ps.executeUpdate();
                        sub=sub +" "+ str+"(P,T)"+" ";
                        }
                        else
                        {
                            backlog++;
                            ps.setInt(1,a);
                            ps.setString(2,str);
                            count_update+=ps.executeUpdate();
                            sub=sub +" "+ str+"(T)"+" ";
                        }
                    }
                    else if(mp<12 && cp>0)
                    {
                        if((mt+mm)<28 && ct>0)
                        {
                        backlog++;
                        ps.setInt(1,a);
                        ps.setString(2,str);
                        count_update+=ps.executeUpdate();
                        sub=sub +" "+ str+"(P,T)"+" ";
                        }
                        else
                        {
                            backlog++;
                            ps.setInt(1,a);
                            ps.setString(2,str);
                            count_update+=ps.executeUpdate();
                            sub=sub +" "+ str+"(P)"+" ";
                        }     
                    }
                    
                    
                    total = total + ((mm+mt+mp)*(cp+ct));
                    count=count+1;
                    cpp = cpp + ct + cp;
                    
                }
                
                ps.close();
                rs.close();
                pst.close();
                System.out.println(sub);
                t3.setText(Integer.toString(backlog)+"   "+sub);
                tc=total/10;
                sgpa=tc/cpp;
                C=cpp;
                T=tc;
                if(b==1)
                {
                    ogpa=sgpa;
                    String q="insert into rps.result values(?,?,?,?,?)";
                    PreparedStatement p=connection.prepareStatement(q);
                    p.setInt(1,a);
                    p.setInt(2,b);
                    p.setInt(3,cpp);
                    p.setString(4,df.format(sgpa));
                    p.setString(5,df.format(ogpa));
                    p.execute();
            JOptionPane.showMessageDialog(null, "Data Saved");
                    p.close();;
                }
                else
                {
                    int c=0;
                    double s=0.0;
                    String q="select * from rps.result";
                    PreparedStatement p=connection.prepareStatement(q);
                    rs=p.executeQuery();
                    while(rs.next() && rs.getInt(2)!=b)
                    {
                        
                        c+=rs.getInt(3);
                        s=rs.getDouble(5);
                        
                    }
                    s=(s*c);
                    System.out.println(c+" "+s);
                    CP=c+cpp;
                    TP=s;
                    ogpa=((s+tc)/(c+cpp));
                    rs.close();
                    p.close();
                    String q2="insert into rps.result values(?,?,?,?,?)";
                    PreparedStatement p2=connection.prepareStatement(q2);
                    p2.setInt(1,a);
                    p2.setInt(2,b);
                    p2.setInt(3,cpp);
                    p2.setString(4,df.format(sgpa));
                    p2.setString(5,df.format(ogpa));
                    p2.execute();
                    JOptionPane.showMessageDialog(null, "Data Saved");
                    p2.close();
                    
                }
                
               OGPA=ogpa;
           
           }catch(Exception e1)
        {
            JOptionPane.showMessageDialog(null,e1);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int a = Integer.parseInt(t1.getText());
        int b = Integer.parseInt(t2.getText());
        PRINT P = new PRINT(a,b,C,T,CP,TP,OGPA);
        Student.this.setVisible(false);
        P.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
